replicaCount: 1

image:
  repository: jobhunt/agent
  tag: latest-dev
  pullPolicy: IfNotPresent

service:
  port: 8001

env:
  API_URL: "http://jobhunt-api:3000"
  AI_CORE_URL: "http://jobhunt-ai-core:8000"
  REDIS_URL: "redis://redis-master:6379"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
