replicaCount: 1

image:
  repository: jobhunt/ai-core
  tag: latest-dev
  pullPolicy: IfNotPresent

service:
  port: 8000

env: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
